initial commit
myakubov1/mcrm-backend pull request #1
Opened 2023-03-26 20:52 UTC by myakubov1

OKAAY, leggo

2023-03-26 21:04 UTC, reuven-yanturin requested changes

2023-03-26 21:04 UTC, reuven-yanturin commented on routers/privateRouter.js
> +privateRouter.get('/clients-p', ClientController.getWithPagination);
первый комент) если хочешь сделать пагинацию, то просто используй ее для роута `GET: /clients`.

проверяй в `query` нужные проперти и если они есть, тогда используй пагинацию.

2023-03-27 20:01 UTC, reuven-yanturin requested changes

2023-03-27 20:01 UTC, reuven-yanturin commented on api/clients/ClientController.js
> +      res.json(client);
когда создаешь сущность, возвращай статус `status(201)`

2023-03-28 00:41 UTC, myakubov1 commented
Уважаемый, я все пофиксил из комментов. Мне аппрувить нужно? Или можно на вторую итерацию ревью как-то отправить?

2023-03-28 19:10 UTC, myakubov1 commented on middleware/AuthMiddleware.js
> +  }
проверка говна. удалил

2023-03-28 20:06 UTC, reuven-yanturin requested changes

2023-03-28 20:06 UTC, reuven-yanturin commented on app.js
> +apiRouter.use('/patients', patientsRouter);
все роуты лучше вытащить в отдельный файл с ройтами как это было раньше

2023-03-28 20:06 UTC, reuven-yanturin commented on middlewares/RoleMiddleware.js
> +      const { roles: userRoles } = jwt.verify(token, process.env.SECRET);
немного не понял с ролями, у юзера могжет быть несколько ролей?

2023-04-11 07:38 UTC, reuven-yanturin commented on middlewares/RoleMiddleware.js
> +      const { roles: userRoles } = jwt.verify(token, process.env.SECRET);
немного не понятная эта логика. лучше всего чтобы у юзера была только одна роль и каждая роль имела разные пермишены.

2023-04-11 07:38 UTC, reuven-yanturin commented on middlewares/RoleMiddleware.js
> +      const { roles: userRoles } = jwt.verify(token, process.env.SECRET);
но эту фитчу можно будет сделать попозже, в отдельном пулл реквесте)

2023-04-11 07:40 UTC, reuven-yanturin approved these changes

2023-04-11 07:40 UTC, merged